#!/usr/bin/python

import sys

# check boto installed and new enough
try:
    import boto
    if boto.Version < '2.0':
        print >>sys.stderr, "You need at least boto 2.0b1 installed to run iboto."
        sys.exit(-1)
except:
    print >>sys.stderr, "You need boto installed to run iboto:\neasy_install boto==2.0b3\nor\npip install boto"
    sys.exit(-1)

from IPython.Shell import IPShellEmbed
args = ['-p','ec2']

banner = """iboto ready

Commands available:
%ec2ssh
%ec2run   (aka %ec2-run-instances)
%ec2start (aka %ec2-start-instances)
%ec2stop  (aka %ec2-stop-instances)
%ec2kill  (aka %ec2-terminate-instances)
%ec2din   (aka %ec2-describe-instances)
%ec2watch
%region

'%command?' for more information.
"""

ipshell = IPShellEmbed(args,
                       banner = banner,
                       exit_msg = 'Leaving iboto')
ipshell()
