#!/usr/bin/env python

import sys

# check boto installed and new enough
try:
    import boto
    major, minor, _ = boto.Version.split('.', 2)
    if 'b' in minor:
        minor, beta = minor.split('b')
        if beta:
            beta = int(beta)
        else:
            beta = 1
    else:
        beta = sys.maxint
    major = int(major)
    minor = int(minor)
    if major < 2 or (major == 2 and minor == 0 and beta < 3):
        print >>sys.stderr, "You need at least boto 2.0b3 installed to run iboto (found %s)." % boto.Version
        sys.exit(-1)
except:
    print >>sys.stderr, "You need boto installed to run iboto:\n$ easy_install boto\nor\n$ pip install boto"
    sys.exit(-1)

try:
    from IPython.Shell import IPShellEmbed
except:
    print >>sys.stderr, "You need ipython installed to run iboto:\n$ easy_install ipython\nor\n$ pip install ipython"
    sys.exit(-1)
args = ['-p','ec2']

banner = """iboto ready

Commands available:
%ec2ssh
%ec2run   (aka %ec2-run-instances)
%ec2start (aka %ec2-start-instances)
%ec2stop  (aka %ec2-stop-instances)
%ec2kill  (aka %ec2-terminate-instances)
%ec2din   (aka %ec2-describe-instances)
%ec2watch
%region

'%command?' for more information.
"""

ipshell = IPShellEmbed(args,
                       banner = banner,
                       exit_msg = 'Leaving iboto')
ipshell()
